services:
  gamera:
    image: ${DOCKER_REGISTRY-}gamera
    container_name: GameRa.Api
    build:
      context: .
      dockerfile: src/API/GameRa/Dockerfile
    ports:
    - 5000:8080
    - 5001:8081

  gamera.database:
   image: postgres:latest
   container_name: GameRa.Database
   environment:
    - POSTGRES_DB=GameRa
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
   volumes:
        - ./containers/db:/var/lib/postgresql/data
   ports:
      - 5432:5432

  gamera.seq:
    image: datalust/seq:latest
    container_name: GameRa.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  gamera.redis:
    image: redis:latest
    container_name: GameRa.Redis
    restart: always
    ports:
      - 6379:6379
  
