<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\GameRa.Common.Presentation\GameRa.Common.Presentation.csproj" />
    <ProjectReference Include="..\..\Games\GameRa.Modules.Games.integrationEvents\GameRa.Modules.Games.IntegrationEvents.csproj" />
    <ProjectReference Include="..\..\User\GameRa.Modules.Users.integrationEvents\GameRa.Modules.Users.IntegrationEvents.csproj" />
    <ProjectReference Include="..\GameRa.Modules.Store.Application\GameRa.Modules.Store.Application.csproj" />
  </ItemGroup>

</Project>
