<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\GameRa.Common.Infrastructure\GameRa.Common.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Common\GameRa.Common.Presentation\GameRa.Common.Presentation.csproj" />
    <ProjectReference Include="..\GameRa.Modules.Discounts.Application\GameRa.Modules.Discounts.Application.csproj" />
    <ProjectReference Include="..\GameRa.Modules.Discounts.Presentation\GameRa.Modules.Discounts.Presentation.csproj" />
    <ProjectReference Include="..\GameRa.Modules.Discounts.PublicApi\GameRa.Modules.Discounts.PublicApi.csproj" />
  </ItemGroup>

</Project>
