<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Games\GetGame.cs" />
  </ItemGroup>
	
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Routing.Abstractions" Version="2.3.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameRa.Modules.Games.Application\GameRa.Modules.Games.Application.csproj" />
  </ItemGroup>

</Project>
